package com.kssasarma.confluencebot.api.dto;

import io.swagger.v3.oas.annotations.media.Schema;

import java.util.List;

@Schema(description = "Chat response containing the answer and the source pages used to generate it")
public record ChatApiResponse(
        @Schema(description = "Answer generated by the LLM, grounded in the retrieved Confluence content",
                example = "To reset your password, navigate to the login page and click Forgot password...")
        String answer,

        @Schema(description = "Confluence pages whose content was retrieved and used as context. "
                + "Empty when no relevant content was found.")
        List<SourceReference> sources
) {
    public static ChatApiResponse noContext() {
        return new ChatApiResponse(
                "I could not find relevant information in the Confluence documentation for your question.",
                List.of()
        );
    }
}
