package com.kssasarma.confluencebot.api.dto;

import io.swagger.v3.oas.annotations.media.Schema;

import java.util.List;

@Schema(description = "Chat response containing the answer, source pages, and suggested follow-up questions")
public record ChatApiResponse(
        @Schema(description = "Answer generated by the LLM, grounded in the retrieved Confluence content",
                example = "To reset your password, navigate to the login page and click Forgot password...")
        String answer,

        @Schema(description = "Confluence pages whose content was retrieved and used as context. "
                + "Empty when no relevant content was found.")
        List<SourceReference> sources,

        @Schema(description = "3 suggested follow-up questions the user might want to ask next. "
                + "Empty when the LLM did not generate them.")
        List<String> followUpQuestions,

        @Schema(description = "Conversation this exchange was recorded in. Null when the caller did "
                + "not supply one, in which case nothing was persisted.")
        String chatId,

        @Schema(description = "Conversation title after this exchange — set from the first question.")
        String title
) {
    /** Backward-compatible constructor for callers that don't need follow-up questions. */
    public ChatApiResponse(String answer, List<SourceReference> sources) {
        this(answer, sources, List.of(), null, null);
    }

    public ChatApiResponse(String answer, List<SourceReference> sources, List<String> followUpQuestions) {
        this(answer, sources, followUpQuestions, null, null);
    }

    /** Same answer, tagged with the conversation it was recorded in. */
    public ChatApiResponse inConversation(String chatId, String title) {
        return new ChatApiResponse(answer, sources, followUpQuestions, chatId, title);
    }

    public static ChatApiResponse noContext() {
        return new ChatApiResponse(NO_CONTEXT_ANSWER, List.of(), List.of(), null, null);
    }

    public static final String NO_CONTEXT_ANSWER =
            "I could not find relevant information in the Confluence documentation for your question.";
}
