package com.kssasarma.confluencebot.api.dto;

import io.swagger.v3.oas.annotations.media.Schema;

import java.util.List;

@Schema(description = "Chat response containing the answer, source pages, citations, "
        + "retrieval confidence and suggested follow-up questions")
public record ChatApiResponse(
        @Schema(description = "Answer generated by the LLM, grounded in the retrieved Confluence content",
                example = "To reset your password, navigate to the login page and click Forgot password [1].")
        String answer,

        @Schema(description = "Confluence pages whose content was retrieved and used as context. "
                + "Empty when no relevant content was found.")
        List<SourceReference> sources,

        @Schema(description = "3 suggested follow-up questions the user might want to ask next. "
                + "Empty when the LLM did not generate them.")
        List<String> followUpQuestions,

        @Schema(description = "Resolves each bracketed marker in the answer to the page it cites. "
                + "Empty when the answer cited nothing.")
        List<Citation> citations,

        @Schema(description = "How well the question matched the indexed documentation, 0–1. "
                + "This measures retrieval quality, NOT whether the answer is correct — an answer "
                + "can be confidently retrieved and still wrong. Null when not computed.",
                example = "0.82")
        Double confidence,

        @Schema(description = "Conversation this exchange was recorded in. Null when the caller did "
                + "not supply one, in which case nothing was persisted.")
        String chatId,

        @Schema(description = "Conversation title after this exchange — set from the first question.")
        String title
) {

    public ChatApiResponse {
        sources = sources == null ? List.of() : List.copyOf(sources);
        followUpQuestions = followUpQuestions == null ? List.of() : List.copyOf(followUpQuestions);
        citations = citations == null ? List.of() : List.copyOf(citations);
    }

    /** Backward-compatible constructor for callers that don't need follow-up questions. */
    public ChatApiResponse(String answer, List<SourceReference> sources) {
        this(answer, sources, List.of(), List.of(), null, null, null);
    }

    public ChatApiResponse(String answer, List<SourceReference> sources, List<String> followUpQuestions) {
        this(answer, sources, followUpQuestions, List.of(), null, null, null);
    }

    /** Same answer, tagged with the conversation it was recorded in. */
    public ChatApiResponse inConversation(String chatId, String title) {
        return new ChatApiResponse(answer, sources, followUpQuestions, citations, confidence, chatId, title);
    }

    /** Same answer, annotated with what it cited and how well retrieval matched. */
    public ChatApiResponse withGrounding(List<Citation> citations, Double confidence) {
        return new ChatApiResponse(answer, sources, followUpQuestions, citations, confidence, chatId, title);
    }

    public static ChatApiResponse noContext() {
        return new ChatApiResponse(NO_CONTEXT_ANSWER, List.of(), List.of(), List.of(), 0.0, null, null);
    }

    public static final String NO_CONTEXT_ANSWER =
            "I could not find relevant information in the Confluence documentation for your question.";
}
